// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function factorial(n) {
  var match = n <= 0;
  if (match) {
    return 1;
  } else {
    return Caml_int32.imul(n, factorial(n - 1 | 0));
  }
}

exports.factorial = factorial;
/* No side effect */
