// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function longestWord(s) {
  var splitted = s.split(" ");
  var maxL = /* record */[/* contents */-1];
  $$Array.iter((function (word) {
          if (word.length > maxL[0]) {
            maxL[0] = word.length;
            return /* () */0;
          } else {
            return 0;
          }
        }), splitted);
  return maxL[0];
}

exports.longestWord = longestWord;
/* No side effect */
