// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function reverse(s) {
  var l = s.length;
  return $$String.init(l, (function (i) {
                return Caml_string.get(s, l - (i + 1 | 0) | 0);
              }));
}

exports.reverse = reverse;
/* No side effect */
