// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var LongestWord$BasicFunctionReason = require("../src/LongestWord.bs.js");

describe("longest word in a string", (function () {
        Jest.test("short", (function () {
                return Jest.Expect[/* toBe */2](6, Jest.Expect[/* expect */0](LongestWord$BasicFunctionReason.longestWord("The quick brown fox jumped over the lazy dog")));
              }));
        return Jest.test("long", (function () {
                      return Jest.Expect[/* toBe */2](19, Jest.Expect[/* expect */0](LongestWord$BasicFunctionReason.longestWord("What if we try a super-long word such as otorhinolaryngology")));
                    }));
      }));

/*  Not a pure module */
