// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Reverse$BasicFunctionReason = require("../src/Reverse.bs.js");

describe("Expect", (function () {
        Jest.test("hello", (function () {
                return Jest.Expect[/* toBe */2]("olleh", Jest.Expect[/* expect */0](Reverse$BasicFunctionReason.reverse("hello")));
              }));
        return Jest.test("ciao", (function () {
                      return Jest.Expect[/* toBe */2]("oaic", Jest.Expect[/* expect */0](Reverse$BasicFunctionReason.reverse("ciao")));
                    }));
      }));

/*  Not a pure module */
